import { 
    ShoppingCart, Fuel, HeartPulse, Lightbulb, Film, PiggyBank, Home, Car, 
    CreditCard, Phone, Utensils, Plane, Grid2X2, Briefcase, Laptop, 
    TrendingUp, Zap, Coffee, Music, Shield, Dumbbell, Shirt, Monitor, 
    Smartphone, Train, ShoppingBag, Gamepad2,
    Grid2x2, Rows3
} from "lucide-react";

export const iconMap: Record<string, React.ReactNode> = {
    "rows": <Rows3 className="w-5 h-5"/>,
    "grid": <Grid2x2 className="w-5 h-5"/>,
    "shopping-cart": <ShoppingCart className="w-5 h-5" />,
    "fuel": <Fuel className="w-5 h-5" />,
    "heart-pulse": <HeartPulse className="w-5 h-5" />,
    "lightbulb": <Lightbulb className="w-5 h-5" />,
    "film": <Film className="w-5 h-5" />,
    "piggy-bank": <PiggyBank className="w-5 h-5" />,
    "home": <Home className="w-5 h-5" />,
    "car": <Car className="w-5 h-5" />,
    "credit-card": <CreditCard className="w-5 h-5" />,
    "phone": <Phone className="w-5 h-5" />,
    "utensils": <Utensils className="w-5 h-5" />,
    "plane": <Plane className="w-5 h-5" />,
    "all": <Grid2X2 className="w-5 h-5"></Grid2X2>,
    "briefcase": <Briefcase className="w-5 h-5" />,
    "laptop": <Laptop className="w-5 h-5" />,
    "trending-up": <TrendingUp className="w-5 h-5" />,
    "zap": <Zap className="w-5 h-5" />,
    "coffee": <Coffee className="w-5 h-5" />,
    "music": <Music className="w-5 h-5" />,
    "shield": <Shield className="w-5 h-5" />,
    "dumbbell": <Dumbbell className="w-5 h-5" />,
    "shirt": <Shirt className="w-5 h-5" />,
    "monitor": <Monitor className="w-5 h-5" />,
    "smartphone": <Smartphone className="w-5 h-5" />,
    "train": <Train className="w-5 h-5" />,
    "shopping-bag": <ShoppingBag className="w-5 h-5" />,
    "gamepad-2": <Gamepad2 className="w-5 h-5" />,
};

export const availableIcons = [
    { id: "shopping-cart", name: "Shopping" },
    { id: "fuel", name: "Fuel" },
    { id: "heart-pulse", name: "Health" },
    { id: "lightbulb", name: "Utilities" },
    { id: "film", name: "Entertainment" },
    { id: "piggy-bank", name: "Savings" },
    { id: "home", name: "Home" },
    { id: "car", name: "Car" },
    { id: "credit-card", name: "Credit" },
    { id: "phone", name: "Phone" },
    { id: "utensils", name: "Food" },
    { id: "plane", name: "Travel" },
    { id: "briefcase", name: "Work" },
    { id: "laptop", name: "Laptop" },
    { id: "trending-up", name: "Investing" },
    { id: "zap", name: "Energy" },
    { id: "coffee", name: "Coffee" },
    { id: "music", name: "Music" },
    { id: "shield", name: "Insurance" },
    { id: "dumbbell", name: "Fitness" },
    { id: "shirt", name: "Clothing" },
    { id: "monitor", name: "Screen" },
    { id: "smartphone", name: "Mobile" },
    { id: "train", name: "Train" },
    { id: "shopping-bag", name: "Bag" },
    { id: "gamepad-2", name: "Gaming" },
];